@extends('layouts.app')

@section('header')
    <div class="event-goal-heading flex flex-wrap items-center gap-3"><div class="event-goal-heading-copy"><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Goal setup</p><h1 class="text-xl font-bold">Goals & progress</h1></div><button type="button" class="btn ml-auto" data-goal-create>+ Add goal</button></div>
@endsection

@section('content')
    <div class="event-goal-page mx-auto max-w-5xl space-y-5 p-4 sm:p-6 lg:p-8">
        <div class="event-goal-introduction panel flex flex-wrap items-center gap-4"><div class="event-goal-introduction-copy min-w-0 flex-1"><h2 class="text-lg font-bold">Your goals</h2><p class="mt-1 text-sm text-slate-500">Choose a goal to edit its target, dates, and progress sources.</p></div><span class="rounded-full bg-indigo-100 px-3 py-1 text-sm font-bold text-indigo-700 dark:bg-indigo-950 dark:text-indigo-200">{{ $goals->count() }} {{ Str::plural('goal', $goals->count()) }}</span></div>
        <section class="space-y-3" data-goal-list>
            @forelse($goals as $goal)
                @php
                    $eventSource = $goal->sources->firstWhere('type', 'event');
                    $githubProjects = $goal->sources->where('type', 'github')->pluck('github_project')->map(fn ($name) => Str::afterLast($name, '/'))->unique()->values();
                    $editor = ['name' => $goal->name, 'emoji' => $goal->emoji, 'color' => $goal->color, 'target_points' => $goal->target_points, 'period' => $goal->period, 'start_date' => $goal->start_date?->toDateString(), 'end_date' => $goal->end_date?->toDateString(), 'manual_enabled' => $goal->manual_enabled, 'task_definition_id' => $eventSource?->task_definition_id, 'github_projects' => $githubProjects, 'update_url' => route('goals.update', $goal), 'delete_url' => route('goals.destroy', $goal)];
                @endphp
                <article class="panel transition hover:border-indigo-300 hover:shadow-md dark:hover:border-indigo-700">
                    <div class="event-goal-row flex w-full items-center gap-3 text-left"><button type="button" class="flex min-w-0 flex-1 items-center gap-3 text-left" data-goal-open="goal-data-{{ $goal->id }}"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-2xl text-2xl shadow-sm" style="background-color:{{ $goal->color }};color:{{ $goal->text_color }}">{{ $goal->emoji }}</span><span class="min-w-0 flex-1"><strong class="block truncate">{{ $goal->name }}</strong><span class="block text-sm text-slate-500">{{ $goal->target_points }} points · {{ $goal->period === 'none' ? 'One time' : ucfirst($goal->period).' reset' }} · {{ $goal->start_date?->format('M j, Y') ?? 'Open start' }} → {{ $goal->end_date?->format('M j, Y') ?? 'Open end' }}</span><span class="mt-1 block text-xs text-slate-400">{{ $eventSource?->taskDefinition?->name ? 'Event: '.$eventSource->taskDefinition->name : '' }}{{ $githubProjects->isNotEmpty() ? ($eventSource ? ' · ' : '').$githubProjects->count().' GitHub '.Str::plural('project', $githubProjects->count()) : '' }}{{ $goal->manual_enabled ? (($eventSource || $githubProjects->isNotEmpty()) ? ' · ' : '').'Manual input' : '' }}</span></span></button><a href="{{ route('goals.show', $goal) }}" class="btn-secondary">Details</a><span class="text-xl text-slate-400">›</span></div>
                    <script type="application/json" id="goal-data-{{ $goal->id }}">@json($editor)</script>
                </article>
            @empty
                <div class="event-goal-empty panel py-12 text-center"><span class="text-4xl">🎯</span><h2 class="mt-3 text-lg font-bold">No goals yet</h2><p class="mt-1 text-sm text-slate-500">Create a target and connect the activity that moves it forward.</p><button type="button" class="btn mt-4" data-goal-create>Create your first goal</button></div>
            @endforelse
        </section>
    </div>

    <div class="event-goal-overlay fixed inset-0 hidden" style="z-index:80" data-overlay="goal-definition" data-overlay-side="right" role="dialog" aria-modal="true" aria-labelledby="goal-definition-title">
        <button type="button" class="absolute inset-0 bg-slate-950/55 opacity-0 transition-opacity" data-overlay-backdrop data-overlay-close="goal-definition" aria-label="Close goal editor"></button>
        <aside class="absolute inset-y-0 right-0 w-full max-w-md translate-x-full overflow-y-auto bg-slate-100 p-4 shadow-2xl transition-transform duration-300 dark:bg-slate-950 sm:p-6" data-overlay-panel>
            <div class="event-goal-editor-heading mb-5 flex items-start gap-2"><div class="event-goal-editor-heading-copy"><p class="text-xs font-bold uppercase tracking-wider text-indigo-600">Goal setup</p><h2 id="goal-definition-title" class="text-2xl font-black" data-goal-title>Add goal</h2><p class="mt-1 text-sm text-slate-500">Set the target and choose what earns points.</p></div><button type="button" class="btn-secondary ml-auto" data-overlay-close="goal-definition">Close</button></div>
            <form method="POST" action="{{ route('goals.store') }}" data-create-action="{{ route('goals.store') }}" class="space-y-4" data-ajax data-goal-form>
                @csrf
                <div class="event-goal-name-field"><label class="label" for="goal-name">Goal name</label><input id="goal-name" class="input" name="name" required placeholder="Ship the weekly release"></div>
                @include('partials.emoji-picker', ['pickerId' => 'goal-emoji', 'name' => 'emoji', 'value' => \App\Models\Goal::DEFAULT_EMOJI, 'label' => 'Goal emoji'])
                <div class="event-goal-color-field"><label class="label" for="goal-color">Goal color</label><div class="event-goal-color-control flex items-center gap-3"><span id="goal-color-preview" class="h-8 w-8 rounded-lg border"></span><input id="goal-color" data-color-input="goal-color-preview" type="color" name="color" value="#4f46e5" class="h-11 w-full cursor-pointer rounded-xl border bg-white p-1 dark:bg-slate-950"></div></div>
                <div class="event-goal-target-period grid grid-cols-2 gap-3"><div class="event-goal-target"><label class="label" for="goal-target">Target points</label><input id="goal-target" class="input" type="number" name="target_points" min="1" value="5" required></div><div class="event-goal-period"><label class="label" for="goal-period">Resets</label><select id="goal-period" class="input" name="period"><option value="weekly">Weekly</option><option value="daily">Daily</option><option value="monthly">Monthly</option><option value="none">Never (one time)</option></select></div></div>
                <div class="event-goal-dates grid grid-cols-2 gap-3"><div class="event-goal-start"><label class="label" for="goal-start">Start <span class="font-normal text-slate-500">(open)</span></label><input id="goal-start" class="input" type="date" name="start_date"></div><div class="event-goal-end"><label class="label" for="goal-end">End <span class="font-normal text-slate-500">(open)</span></label><input id="goal-end" class="input" type="date" name="end_date"></div></div>
                <fieldset class="space-y-4 rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><legend class="px-1 text-sm font-bold">Progress sources</legend>
                    <div class="event-goal-event-source"><label class="label" for="goal-event-source">Existing event (+1 each)</label><select id="goal-event-source" class="input" name="task_definition_id"><option value="">No event linked</option>@foreach($tasks as $task)<option value="{{ $task->id }}">{{ $task->emoji }} {{ $task->name }}</option>@endforeach</select></div>
                    <div class="event-goal-github-source" data-goal-project-picker><label class="label" for="goal-project-filter">GitHub projects (+1 per commit)</label><input id="goal-project-filter" class="input" type="search" placeholder="Filter projects…" data-goal-project-filter><div class="event-goal-project-list mt-2 max-h-44 space-y-1 overflow-y-auto rounded-xl border border-slate-200 bg-white p-1 dark:border-slate-700 dark:bg-slate-900" data-goal-project-list>@forelse($projects as $project)<button type="button" class="group flex w-full items-center rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-100 disabled:opacity-40 dark:hover:bg-slate-800" data-goal-project-add="{{ $project }}"><span class="min-w-0 flex-1 truncate">{{ $project }}</span><span class="ml-2 rounded-lg bg-indigo-600 px-2 py-1 text-xs font-bold text-white opacity-100 transition sm:opacity-0 sm:group-hover:opacity-100 sm:group-focus:opacity-100">Add</span></button>@empty<p class="px-3 py-4 text-center text-xs text-slate-500">No synced GitHub projects yet.</p>@endforelse</div><p class="mt-2 text-xs font-semibold text-slate-500">Added projects</p><div class="event-goal-project-selected mt-2 flex min-h-8 flex-wrap gap-2" data-goal-project-selected></div><div class="event-goal-project-inputs" data-goal-project-inputs></div></div>
                    <label class="flex gap-2 text-sm"><input type="checkbox" name="manual_enabled" value="1"><span><strong>Allow manual points</strong><span class="block text-xs text-slate-500">Add a note and a custom positive point value on the detail page.</span></span></label>
                </fieldset>
                <button class="btn w-full" data-goal-submit>Create goal</button>
            </form>
            <div class="event-goal-delete mt-7 hidden border-t border-slate-200 pt-5 dark:border-slate-800" data-goal-delete-section><form method="POST" action="" data-goal-delete-form data-confirm-delete data-confirm-title="Delete this goal?" data-confirm-message="The goal and its progress history will be deleted. Original logs and tracked events will stay unchanged." data-confirm-text="Delete goal">@csrf @method('DELETE')<button class="btn-secondary w-full border-rose-300 text-rose-600">Delete goal</button></form><p class="mt-2 text-center text-xs text-slate-500">Original logs and events are not changed.</p></div>
        </aside>
    </div>
@endsection
