@extends('layouts.app')

@section('header')
    <div id="goal-detail-heading" class="flex flex-wrap items-center gap-3"><span class="grid h-11 w-11 place-items-center rounded-2xl text-2xl" style="background-color:{{ $goal->color }};color:{{ $goal->text_color }}">{{ $goal->emoji }}</span><div id="goal-detail-heading-copy"><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Goal details</p><h1 class="text-xl font-bold">{{ $goal->name }}</h1></div><a class="btn-secondary ml-auto" href="{{ route('goals.index') }}">Goal setup</a></div>
@endsection

@section('content')
    @php $step = $goal->period === 'monthly' ? 'month' : ($goal->period === 'daily' ? 'day' : 'week'); @endphp
    <div id="goal-detail-page" class="mx-auto max-w-5xl space-y-5 p-4 sm:p-6 lg:p-8">
        <div class="event-goal-navigation flex flex-wrap gap-2"><a class="btn-secondary" href="{{ route('goals.show', ['goal' => $goal, 'date' => $date->copy()->sub(1, $step)->toDateString()]) }}">← Previous period</a><a class="btn-secondary" href="{{ route('goals.show', $goal) }}">Current</a><a class="btn-secondary" href="{{ route('goals.show', ['goal' => $goal, 'date' => $date->copy()->add(1, $step)->toDateString()]) }}">Next period →</a><a class="btn-secondary ml-auto" href="{{ route('calendar', $date->toDateString()) }}">View calendar</a></div>
        <section class="panel"><div id="goal-progress-summary" class="flex flex-wrap items-end justify-between gap-3"><div id="goal-progress-copy"><p class="text-sm text-slate-500">{{ $snapshot['period_start']?->format('M j, Y') ?? 'Open start' }} – {{ $snapshot['period_end']?->format('M j, Y') ?? 'Open end' }}</p><p class="mt-1 text-3xl font-black">{{ $snapshot['points'] }} <span class="text-lg font-semibold text-slate-500">/ {{ $snapshot['target'] }} points</span></p></div><span class="rounded-full px-3 py-1 text-sm font-bold {{ $snapshot['complete'] ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300' }}">{{ $snapshot['complete'] ? 'Complete' : $snapshot['percent'].'%' }}</span></div><div id="goal-progress-track" class="mt-4 h-3 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-800"><div id="goal-progress-fill" class="h-full rounded-full" style="width:{{ $snapshot['percent'] }}%; background-color:{{ $goal->color }};"></div></div><p class="mt-3 text-sm text-slate-500">{{ ucfirst($goal->period === 'none' ? 'one-time' : $goal->period) }} goal · {{ $goal->start_date?->format('M j, Y') ?? 'open start' }} → {{ $goal->end_date?->format('M j, Y') ?? 'open end' }}{{ $snapshot['latest'] ? ' · Last activity '.$snapshot['latest']->occurred_at->diffForHumans() : '' }}</p></section>
        <section class="panel"><h2 class="text-lg font-bold">Progress sources</h2><p class="mt-3 flex flex-wrap gap-2">@foreach($goal->sources as $source)<span class="rounded-full bg-slate-100 px-3 py-1 text-sm dark:bg-slate-800">{{ $source->type === 'event' ? '✅ Event: '.($source->taskDefinition?->name ?? 'deleted event') : '💻 GitHub: '.Str::afterLast($source->github_project, '/') }}</span>@endforeach @if($goal->manual_enabled)<span class="rounded-full bg-slate-100 px-3 py-1 text-sm dark:bg-slate-800">✍️ Manual points</span>@endif @if($goal->sources->isEmpty() && ! $goal->manual_enabled)<span class="text-sm text-slate-500">No progress source configured.</span>@endif</p></section>
        @if($goal->manual_enabled)<section class="panel"><h2 class="text-lg font-bold">Add progress</h2><form method="POST" action="{{ route('goals.entries.store', $goal) }}" class="mt-4 grid gap-3 sm:grid-cols-[8rem_10rem_1fr_auto]">@csrf<div class="event-goal-manual-points"><label class="label" for="goal-entry-points">Points</label><input id="goal-entry-points" class="input" type="number" name="points" min="1" value="1" required></div><div class="event-goal-manual-date"><label class="label" for="goal-entry-date">Date</label><input id="goal-entry-date" class="input" type="date" name="occurred_on" value="{{ $date->toDateString() }}" required></div><div class="event-goal-manual-note"><label class="label" for="goal-entry-note">What happened?</label><input id="goal-entry-note" class="input" name="note" maxlength="2000" placeholder="Finished the draft"></div><button class="btn self-end">Add</button></form></section>@endif
        <div class="event-goal-columns grid gap-5 lg:grid-cols-2"><section class="panel"><h2 class="text-lg font-bold">Activity in this period</h2><div class="event-goal-activity mt-4 space-y-3">@forelse($snapshot['entries'] as $entry)<div class="event-goal-entry flex items-start gap-3 border-b border-slate-100 pb-3 last:border-0 dark:border-slate-800"><span class="rounded-full bg-indigo-100 px-2 py-1 text-xs font-bold text-indigo-700">+{{ $entry->points }}</span><div class="event-goal-entry-copy min-w-0"><p class="break-words text-sm font-semibold">{{ $entry->note ?: 'Manual progress' }}</p><p class="text-xs text-slate-500">{{ $entry->source?->type ? ucfirst($entry->source->type) : 'Manual' }} · {{ $entry->occurred_at->format('M j, Y H:i') }}</p></div></div>@empty<p class="text-sm text-slate-500">No progress recorded in this period.</p>@endforelse</div></section><section class="panel"><h2 class="text-lg font-bold">Period history</h2><div class="event-goal-history mt-4 space-y-2">@foreach($history as $period)<a class="flex items-center justify-between rounded-xl border border-slate-200 p-3 hover:border-indigo-400 dark:border-slate-700" href="{{ route('goals.show', ['goal' => $goal, 'date' => ($period['period_start'] ?? $date)->toDateString()]) }}"><span class="text-sm">{{ $period['period_start']?->format('M j') ?? 'Open' }} – {{ $period['period_end']?->format('M j, Y') ?? 'Open' }}</span><strong>{{ $period['points'] }}/{{ $period['target'] }}</strong></a>@endforeach</div></section></div>
    </div>
@endsection
